server {
    listen 80;
    server_name _;

    location /live/ {
        alias /var/www/asiftechglobal-hls/;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Cache-Control "no-store" always;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
    }
}
